### ISSUE TITLE
All test failures should always be reported

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/go-test-runner#47]
I am solving Cars Assemble and I was really confused that there are no tests for the third function, `CalculateProductionRatePerMinute`. Here is the test output of a partial solution, 6 passed, 2 failed:
![Screenshot 2021-10-02 at 19-26-43 Exercism](https://user-images.githubusercontent.com/7852553/135726650-32b9b327-5f02-42d1-a1f4-ba9a801840c7.png)

Then, after I implemented the second function correctly, suddenly the tests for `CalculateProductionRatePerMinute` appeared. The results are now 8 tests passed, 6 failed = 6 more tests than the last time?

![Screenshot 2021-10-02 at 19-26-16 Exercism](https://user-images.githubusercontent.com/7852553/135726666-3a4a1ed5-8f27-4a70-ba9b-5799e58b5feb.png)

I didn't see anything that would explain this behavior in the test file itself https://github.com/exercism/go/blob/main/exercises/concept/cars-assemble/cars_assemble_test.go that's why I decided to open an issue in this repo, not in the exercises repo. But I might we wrong.

**Comment by junedev** [comment]
Explanation what's going on:  
`CalculateProductionRatePerMinute` has 5 subtests. Due to the `panic` in the code those are not executed in the first screenshot. You only see the failure of the parent test.  
In the second screenshot there is no panic anymore, the subtests are executed so there are 6 tests now, the parent and the 5 subtests.

I don't really have a good idea what to do about this. We could replace the panic with returning the zero (default) value of the result, e.g.
```go
func CalculateProductionRatePerHour(speed int) float64 {
        // TODO: implement the CalculateProductionRatePerHour
	return 0
}
```
But this could mean that some tests already pass without the student writing any code which is also confusing.

**Comment by andrerfcsantos** [comment]
> But this could mean that some tests already pass without the student writing any code which is also confusing.

I like the idea of returning a value. To make the possibility of returning the zero value pass some tests less of a concern, I think what we can do is to have some constants defined in the tests that we know will fail the tests, and in the stub implementation, just return those constants.

For instance, in this example and for the `CalculateProductionRatePerHour` function. In the test file we can have something like:

```go
// define a constant that will fail all the tests
const ImplmentProductionRatePerHour = 999999.0
```

And then in the function:

```go
func CalculateProductionRatePerHour(speed int) float64 {
        // TODO: implement the CalculateProductionRatePerHour
	return ImplmentProductionRatePerHour
}
```

My only fear is that with this solution students can be tempted to use `ImplmentProductionRatePerHour` as a variable themselves and not realize they are supposed to re-write everything.
